### ISSUE TITLE
Chart advice

### ISSUE THREAD

**Issue by DarkBlaez** [FusionAuth/charts#32]
It is possible to put Postgres and Elasticsearch back in the chart and use a bool for enable: etc to pull in as needed. This creates a chart that can be spun up fully without external dependencies or allow external instances. Just an opinion.

Also what is the desired result for these sections. They do not work as one expects

  To use an existing secret, set `existingSecret` to the name of the secret. We expect two keys: `password` and `rootpassword`
  existingSecret: "" <----- If this is filled in then the next fields should be ignored, not required
  user: ""
  password: ""

  These credentials are used for bootstrapping the database
  root:
    user: "" <----- if the secret is filled in then this should be ignored (?)
    password: ""

search:
  Valid values for engine are 'elasticsearch' or (if you are using fusionauth >= 1.16.0-rc.1) 'database'.
  engine: elasticsearch <----- If you place database here should this not cause the host field to be ignored?
  protocol: http
  host: ""

If seems to me that the helm chart needs more attention. The trend is moving away from docker to using full orchestration on the desktop to use Kubernetes. Docker by itself is great for doing actual development of said product but the evolution is towards providing the following supported options, docker, Kubernetes manifest, Kubernetes Helm. Manfiset and Helm tend to get ignored because many have trouble creating them for some reason.

Advise on what you want the expected behavior to be in the Helm chart and I will develop these further and submit a pull request

DB

**Comment by drpebcak** [comment]
> It is possible to put Postgres and Elasticsearch back in the chart and use a bool for enable: etc to pull in as needed. This creates a chart that can be spun up fully without external dependencies or allow external instances. Just an opinion.

I would rather not, because managing those dependencies makes this chart a lot heavier. Having to keep those up to date and then worry about breaking changes inside those downstream charts is more work than it is worth. I personally also don't like tying state into a chart for a stateless service.

> Also what is the desired result for these sections. They do not work as one expects
> 
> To use an existing secret, set existingSecret to the name of the secret. We expect two keys: password and rootpassword
existingSecret: "" <----- If this is filled in then the next fields should be ignored, not required
user: ""
password: ""
> 
> These credentials are used for bootstrapping the database
root:
user: "" <----- if the secret is filled in then this should be ignored (?)
password: ""

Not sure what you are getting at here. The user is still required - only the passwords are coming from the secret. The comment says: We expect two keys: `password` and `rootpassword`. I've seen secrets done both ways - with the username as part of the secret and not. Is the comment not clear that we are only filling in `password` and `rootpassword`?

> search:
Valid values for engine are 'elasticsearch' or (if you are using fusionauth >= 1.16.0-rc.1) 'database'.
engine: elasticsearch <----- If you place database here should this not cause the host field to be ignored?
protocol: http
host: ""

This is how it works, isn't it? If you set search.engine=database, nothing that uses search.host is used.

**Comment by DarkBlaez** [comment]
Actually the chart is not working correctly. Deploy with "database" over "Elasticsearch" and check the logs, there are exceptions thrown. Also, the reasoning behind the chart inclusion actually does not hold merit. Being able to include as needed has never been much of an issue for other maintainers or projects, to include competitors. It's a very simple task if helm is well understood. However, what I will do is reformulate the charts and publish an alternative set which mirror what others are doing. Thanks for the clarification

DB

**Comment by drpebcak** [comment]
The issue you are referring to doesn't have anything to do with the chart, it was an issue in the default version of the application. You can see it being discussed here: https://github.com/FusionAuth/fusionauth-issues/issues/851

We can of course bump up the version of fusionauth we are installing.

**Comment by DarkBlaez** [comment]
If that is the issue then we should bump the version being pulled

Thanks
DB

**Comment by drpebcak** [comment]
Just did it.
