### ISSUE TITLE
apiVersion bumped to 2?

### ISSUE THREAD

**Issue by nodesocket** [FusionAuth/charts#41]
Why is Helm api version changed to `apiVersion: v2` in the latest commit? Does that mean Helm version 2 is no longer supported?

**Comment by drpebcak** [comment]
As of the 13th, helm 2 is officially completely EOL. While there isn't anything in this chart that specifically does not work in helm 2 ( as far as I know), I don't use helm 2 anymore, and so I can't say for sure whether or not it works.

Because it's completely EOL though, everyone who is still using helm 2 should consider updating immediately.
